apiVersion: "v1"
kind: "Secret"
metadata:
  name: "gitlab-root-secret"
stringData:
  password: "secret00!"
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "gitlab-smtp"
stringData:
  username: "..."
  password: "..."
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
stringData:
  accessKey: "aaaaaa"
  secretKey: "xxxxxxxxxx"
---
apiVersion: "glasskube.eu/v1alpha1"
kind: "Gitlab"
metadata:
  name: "gitlab"
spec:
  database: 
    storage: 
      size: 21Gi
  version: "16.9.1"
  omnibusConfigOverride: |+
    postgresql['enable'] = false

    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'unicode'
    gitlab_rails['db_host'] = ENV['DB_HOST']
    gitlab_rails['db_password'] = ENV['DB_PASSWORD']

    gitlab_rails['initial_root_password'] = ENV['INITIAL_ROOT_PASSWORD']

    external_url "http://" + ENV['GITLAB_HOST']
    gitlab_rails['gitlab_ssh_host'] = ENV['GITLAB_SSH_HOST']

    puma['worker_processes'] = 0
    sidekiq['max_concurrency'] = 10
    nginx['worker_processes'] = 2
    nginx['listen_https'] = false
    nginx['listen_port'] = 80
    nginx['real_ip_trusted_addresses'] = ['0.0.0.0/0']
    # nginx['proxy_set_headers'] = {
    #     "X-Forwarded-Proto" => "http",
    #     "X-Forwarded-Port" => "80",
    #     "Host" => ENV['GITLAB_HOST']
    # }
    nginx['server_names_hash_bucket_size'] = 128



  initialRootPasswordSecret:
    name: gitlab-root-secret
    key: password
  resources:
    claims:
      - name: gitlab-gitlab-data2
      # - size: 20Gi

      # name: 
      #   gitlab-gitlab-data: 20Gi


    limits:
      cpu: 4000m
      memory: 6000Mi
    requests:
      cpu: 2000m
      memory: 4000Mi
  host: "gitlab1.demo"
  sshEnabled: true
  sshHost: "172.20.0.102"