apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-deployment
  template:
    metadata:
      labels:
        app: demo-deployment
    spec:
      containers:
      - name: demo
        image: gcr.io/playground-s-11-6e2c7a0e/static-site:660aa198d87d896a8a90ba602c19abfa54f0c4d3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m